### ISSUE TITLE
PARDISO Iterative solver?

### ISSUE THREAD

**Issue by 3rav** [Dhondtguido/CalculiX#20]
In the modification for version 2.9, the option for PARDISO solver `8: iterpardiso` has been added, maybe it's worth adding something like this to the base version?

Modification add `LIS` solver and `PARDISO Iterative solver`: https://sites.google.com/site/kodanda/research/calculix-addons

**Comment by victorkemp** [comment]
I don't think Pardiso Solver Project's version of Pardiso is necessarily very good for FEA compared to the MKL version. It has spectacular looking benchmarks but they are all for circuit analysis which tends to have much narrower bandwidth matrices than FEA, so its advantage there might not apply here at all.
