### ISSUE TITLE
Formula error on the manual.

### ISSUE THREAD

**Issue by disla2** [Dhondtguido/CalculiX#22]
![imagen](https://user-images.githubusercontent.com/126724892/222271119-f8c12011-48b0-41d4-b37d-250ea2ba7b91.png)

Errors in formulas 711 and 712 of ccx manual 2.20 .

Where it says -1/3 it should say -2/3 and -4/3

**Comment by FEA-eng** [comment]
There are quite a few typos and mistakes in the ccx manual. @Dhondtguido said that he will create a separate repository with the documentation where we could create issues (or possible PRs) to correct such mistakes. Unfortunately, this repository hasn't been created yet.

**Comment by Dhondtguido** [comment]
Hi,
formula (711) is correct in the manual (power -1/3), formula (712), however, is not, the power should be -2/3. Recall that III_C = J^2.
Thanks for pointing this out.

Guido
