### ISSUE TITLE
CYCLIC SYMMETRY MODEL parameter NGRAPH behavior

### ISSUE THREAD

**Issue by OliverKunc** [Dhondtguido/CalculiX#32]
The parameter `NGRAPH` of the `*CYCLIC SYMMETRY MODEL` card seems to lose effect when there is first a `*STEP` with a `*FREQUENCY` analysis _without_ `*SELECT CYCLIC SYMMETRY MODES`.

Even if there is a subsequent `*STEP` with `*FREQUENCY` and _with_ `*SELECT CYCLIC SYMMETRY MODES`, still only one segment of the model is output to the .frd file.

Only if there are exclusively `*STEP`s _with_ `*SELECT CYCLIC SYMMETRY MODES` the parameter `NGRAPH` takes effect.

Steps to reproduce: see the example **fullseg.inp**. Change `NGRAPH` to a value larger than one and remove the first occurrence of `*SELECT CYCLIC SYMMETRY MODES`. Then the .frd file has only one segment.

Expected behavior, two possibilities:

1. `NGRAPH `should take effect when there is no `*SELECT CYCLIC SYMMETRY MODES`, or
2. `NGRAPH `should take effect when there is a `*SELECT CYCLIC SYMMETRY MODES` keyword even if it was preceded by a step without this keyword.

**Comment by victorkemp** [comment]
Does it make sense to have a *FREQUENCY step without *SELECT CYCLIC SYMMETRY MODES when you've defined *CYCLIC SYMMETRY MODEL? What does the solution from that mean?

**Comment by OliverKunc** [comment]
@victorkemp The solution is equivalent to that of `*SELECT CYCLIC SYMMETRY MODES,NMIN=0,NMAX=0`, i.e. nodal diameter zero. Just to be 100% sure, I have checked this with the fullseg.inp example for the first couple eigenmodes.

It is not exactly the same because `*SELECT CYCLIC SYMMETRY MODES,NMIN=0,NMAX=0` results in a (arbitrary?) split of the displacements into a real and an imaginary part with constant phase difference. The lack of `*SELECT CYCLIC SYMMETRY MODES,NMIN=0,NMAX=0` gives just one single, real displacement field, which is what makes most sense.

However, there is also a slight difference in the frequency. That I don't fully understand, possibly some round-off issue.

**Comment by FEA-eng** [comment]
Another issue regarding this parameter: #33

**Comment by Dhondtguido** [comment]
Hi Oliver,
in a calculation with *CYCLIC SYMMETRY MODEL the *SELECT CYCLIC SYMMETRY MODES should be used. You are right that you can do without for nodal diameter zero and that NGRAPH does not work in that case, however, taking care of this special issue is not on the top of my list.
Thanks for pointing this out,
Guido
