### ISSUE TITLE
NGRAPH doesn’t work properly for the second cyclic symmetry definition

### ISSUE THREAD

**Issue by FEA-eng** [Dhondtguido/CalculiX#33]
I’ve noticed that the NGRAPH parameter doesn’t work properly for the second definition of cyclic symmetry. Multiple cyclic symmetries seem to work properly in CalculiX (even though there are some warnings regarding accuracy in the documentation) but visualization is broken for the second instance of cyclic symmetry. Here are the exemplary results with NGRAPH=1 for both cyclic symmetry definitions:

![single](https://github.com/Dhondtguido/CalculiX/assets/59876896/8bfbab85-2017-4810-9f9c-1d4e8de10358)

and here are the results for the same case but with NGRAPH equal to the number of sectors (6 for the left part and 12 for the right one):

![multiple](https://github.com/Dhondtguido/CalculiX/assets/59876896/e19f1262-f627-4b00-a60b-b904fd2df38b)

It seems that it takes the wrong axis (the one used for the first cyclic symmetry definition) and does some additional transformation.

If the first part is removed, the visualization works correctly for the second one. It happens also with other models.

Here’s the input file: [Dropbox - Ngraph_issue.inp - Simplify your life](https://www.dropbox.com/s/vr7wqnve96uij8a/Ngraph_issue.inp?dl=0)

Forum thread: https://calculix.discourse.group/t/ngraph-doesnt-work-properly-for-the-second-cyclic-symmetry-definition/1675

**Comment by Dhondtguido** [comment]
Hi,
several cyclic symmetry definitions should be about one and the same axis, different axes are not allowed. I changed the documentation slightly to emphasize this.

Best,

Guido
