### ISSUE TITLE
 Strain Energy density Neo Hookean / Mooney Rivlin

### ISSUE THREAD

**Issue by disla2** [Dhondtguido/CalculiX#35]
Hello Mr. Dhondt

Strain Energy density final value deviates from analytical solution for hyperelastic models Neo Hookean and Mooney Rivling with (C01=0). Issue could extend to Polynomial and relatives. 
Analytical solution= 0.525 MPa (Confirmed with Abaqus)
Result = 0.79 MPa

Nominal stress and Strain curves agree with expected solution but not the final Strain Energy density computation.
As a Hyperelastic model, strain energy density is a potential and I would expect solution only depends on final state  (stretch lambda_u and C10 coefficient).
I would appreciate if you could look at it.

Forum thread: https://calculix.discourse.group/t/strain-energy-density-neo-hookean-mooney-rivlin/1686

[Hyperelastic Neo Hookean Mooney-Rivlin Strain Energy .pdf](https://github.com/Dhondtguido/CalculiX/files/11621790/Hyperelastic.Neo.Hookean.Mooney-Rivlin.Strain.Energy.pdf)

`*NODE
1,0,0,0.1
2,0,0,0
3,1,0,0.1
4,1,0,0
5,0,-0.1,0.1
6,1,-0.1,0
7,0,-0.1,0
8,1,-0.1,0.1
*ELEMENT,TYPE=C3D8
1,6,8,3,4,7,5,1,2
*ELSET,ELSET=Hexahedral
1
*SURFACE,NAME=Moving_face
1,S1
*SURFACE,NAME=Base
1,S2
*MATERIAL,NAME=Neo_Hook
*HYPERELASTIC,NEO HOOKE
900000,2E-10
*MATERIAL,NAME=Mooney_Rivlin
*HYPERELASTIC,MOONEY-RIVLIN
900000,0,2E-10
*SOLID SECTION,ELSET=Hexahedral,MATERIAL=Mooney_Rivlin
*BOUNDARY
1,1,,0
1,2,,0
2,1,,0
2,2,,0
2,3,,0
3,2,,0
4,2,,0
4,3,,0
5,1,,0
6,3,,0
7,1,,0
7,3,,0
*AMPLITUDE,NAME=A_1
0,0
500,-0.5
*TIME POINTS,NAME=timepointsname
1
*STEP,NLGEOM=YES,INC=110,AMPLITUDE=STEP
*STATIC
5,500,0,5
*BOUNDARY,AMPLITUDE=A_1
3,1,,-1
*BOUNDARY,AMPLITUDE=A_1
4,1,,-1
*BOUNDARY,AMPLITUDE=A_1
6,1,,-1
*BOUNDARY,AMPLITUDE=A_1
8,1,,-1
*NODE FILE,GLOBAL=YES,TIME POINTS=timepointsname
U,RF
*EL FILE,TIME POINTS=timepointsname
S,NOE,ENER,E
*EL FILE 
ENER

*EL PRINT, ELSET=Hexahedral
ENER
*END STEP`

**Comment by Dhondtguido** [comment]
Hi disla2,
I had a look at this problem. Due to the TIME POINTS parameter  the energy is indeed not correctly calculated. I corrected the error, the correction will be available in the next update, probably at the end of July 2023.
Thanks for pointing this out,

Guido
