### ISSUE TITLE
*ERROR in cascade for *BOUNDARY on rotated rectangular beam.

### ISSUE THREAD

**Issue by victorkemp** [Dhondtguido/CalculiX#37]
The following example

```
*NODE
1,0,0,0
2,1,1,0
*ELEMENT,TYPE=B31,ELSET=Eall
1,1,2
*MATERIAL,NAME=Material
*ELASTIC,TYPE=ISOTROPIC
210000000000,0
*BEAM SECTION,ELSET=Eall,MATERIAL=Material,SECTION=RECT
0.15,0.1
-1,1,0
*BOUNDARY
2,1,6,0
*STEP
*STATIC
*END STEP
```

fails with 

```
*ERROR in cascade: zero coefficient on the
        dependent side of an equation
        dependent node: 14        direction: 3

```

but it shouldn't.
![image](https://github.com/Dhondtguido/CalculiX/assets/118495694/7033a2de-1650-4ade-8e63-328f57e4ebc2)

**Comment by Dhondtguido** [comment]
Hi Victor,

I think I found a solution to that. Do you allow me to include your simple examples in the test suite?

Thanks for all your contributions, they are very valuable!

Best Greetings,

Guido

**Comment by victorkemp** [comment]
Fantastic. Thanks for fixing it properly!

Yes, feel free to use any code or examples from my issues or pull requests without attribution. Any copyright I have to them, I give up to public domain.
