### ISSUE TITLE
*ERROR in cascade for *BOUNDARY on rotated rectangular beam with 3 DOFs constrained.

### ISSUE THREAD

**Issue by victorkemp** [Dhondtguido/CalculiX#40]
This file with a rectangular beam at a funny angle fails with

*ERROR in cascade: zero coefficient on the
        dependent side of an equation
        dependent node: 5        direction: 3

It's not fixed by my bugfix (https://github.com/Dhondtguido/CalculiX/pull/39) for the similar issue https://github.com/Dhondtguido/CalculiX/issues/37 

```
*NODE
1,0,0,0
2,0.7,1.4,-2
*ELEMENT,TYPE=B31,ELSET=Eall
1,1,2
*MATERIAL,NAME=Material
*ELASTIC,TYPE=ISOTROPIC
200000000000,0
*BEAM SECTION,ELSET=Eall,MATERIAL=Material,SECTION=RECT
0.1,0.3
-0.894427191,0.447213595499,0
*BOUNDARY
1,4,6,0
*STEP
*STATIC
*END STEP
```

Accidental dupe of https://github.com/Dhondtguido/CalculiX/issues/18

**Comment by Dhondtguido** [comment]
Hi Victor,
thanks for the many hints and solution proposals. In this case,however, the beam can freely translate and the solution is indeterminate. I would like to concentrate on the example in which all dofs from 1 to 6 were restrained.
Best,

Guido
