### ISSUE TITLE
Support VTK/VTU/PVD result files

### ISSUE THREAD

**Issue by lcheng9** [Dhondtguido/CalculiX#80]
In addition to the DAT and FRD result files, is possible to support VTK-like result files? such as allow a command to generate VTK-like format results. Thanks.

**Comment by FEA-eng** [comment]
This is 3rd part format so I doubt it will be implemented. Fortunately, there are some converters like this one: https://github.com/calculix/ccx2paraview

**Comment by NorbertHofbauer** [comment]
@lcheng9 you could also take a look at the component for cubit. 
https://github.com/calculix/Cubit-CalculiX

The .frd and .dat results gets converted to vtpc for paraview. You can distinguish between parts, nodesets, sidesets in the multiblock inspector. Also the integraton point data will be converted.
